#!/bin/sh

set -eu

/usr/bin/setprop ctl.start neuralnetworks_hal_service_mtk_neuron

for i in $(seq 1 30); do
    if /usr/bin/binder-list | /usr/bin/grep -q "android.hardware.neuralnetworks@1.3::IDevice/mtk-neuron"; then
        exit 0
    fi
    sleep 1
done

echo "mtk NN binder service not found"
exit 1
